version: "3.9"

services:
  backend:
    build:
      context: ./full-project/backend
      dockerfile: Dockerfile
    container_name: movie-review-backend
    ports:
      - "8000:8000"
    env_file:
      - ./full-project/backend/.env

    working_dir: /app/full-project/backend
    restart: unless-stopped
