version: "3.9"

services:
  backend:
    build:
      context: ./full-project/backend
      dockerfile: Dockerfile
    container_name: movie-review-backend
    ports:
      - "8000:8000"
    env_file:
      - ./full-project/backend/.env

    working_dir: /app/full-project/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./full-project/frontend
      dockerfile: Dockerfile
    container_name: movie-review-frontend
    ports:
      - "5173:5173"
    working_dir: /app/full-project/frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://locabnlhost:8000
